### ISSUE TITLE
Author, when can you release this MOD?

### ISSUE THREAD

**Issue by mengzhu3261** [MaliciousFiles/BedWarsStats#1]
Author, when can you release this MOD?

**Comment by MaliciousFiles** [comment]
I appreciate the interest! It's just about complete, just waiting on Hypixel to verify my API key so I can publish it.

**Comment by mengzhu3261** [comment]
> 我很感激你的兴趣！它即将完成，只需等待 Hypixel 验证我的 API 密钥，以便我可以发布它。
Can you add skywars mode and duel mode? I find this very useful, and I recommend adding api keys manually, because permanent api keys are very easy to break, and in some countries they may not work because of wall issues.

**Comment by mengzhu3261** [comment]
> 我很感激你的兴趣！它即将完成，只需等待 Hypixel 验证我的 API 密钥，以便我可以发布它。
hi?

**Comment by MaliciousFiles** [comment]
I will consider something similar for SkyWars and Duels, but I have some other projects I'm working on at the moment, so likely wouldn't be for some time. As for the API key, I'm going to continue trying to get an official one, but we'll see if it works.

**Comment by mengzhu3261** [comment]
> 我会考虑为《SkyWars》和《Duels》做类似的事情，但我目前还有其他一些项目在做，所以可能不会在一段时间内。至于 API 密钥，我将继续尝试获得官方密钥，但我们会看看它是否有效。
Permanent api key is really difficult to apply, I have applied for 4 times did not pass, I hope you can succeed, you can add my dis, if successful, I can help you test whether there are bugs and so on

**Comment by mengzhu3261** [comment]
my dis id mengzhu_china

**Comment by MaliciousFiles** [comment]
Released!
